source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'
use_frameworks! :linkage => :static
use_modular_headers!

target 'CicadaDemo' do
    pod 'AFNetworking'
    pod 'IQKeyboardManager'
    pod 'MJExtension'
    pod 'MBProgressHUD'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = false
         end
    end
  end
end
